Fix postinst error HYP-20553
ERROR: hydraip-prodimage-1.0-r0 do_rootfs: Postinstall scriptlets of
['init-ifupdown'] have failed. If the intention is to defer them to
first boot, then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Signed-off-by: Mario Schuknecht <mario.schuknecht@dresearch-fe.de>