Fix dependency for congatec-tca5-64 HYP-17946
Fix unbuildable dependency:
ERROR: Nothing RPROVIDES 'initramfs-module-install'
NOTE: Runtime target 'initramfs-module-install' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['initramfs-module-install']
ERROR: Required build target 'hipos-prodimage' has no buildable providers.
Missing or unbuildable dependency chain was: ['hipos-prodimage', 'core-image-minimal-initramfs', 'initramfs-module-install']

Use initramfs-framework instead of initramfs-live.

Signed-off-by: Mario Schuknecht <mario.schuknecht@dresearch-fe.de>