Remove 'qt3d' from image HYP-22728
Sometimes the following error occurs when compiling 'qt3d':
| make: *** [Makefile:101: sub-examples-make_first] Error 2
| WARNING: qt3d/5.13.2+gitAUTOINC+93361f1a59-r0/temp/run.do_compile.6813:1 exit 1 from 'exit 1'
|
NOTE: recipe qt3d-5.13.2+gitAUTOINC+93361f1a59-r0: task do_compile: Failed
ERROR: Task (meta-qt5/recipes-qt/qt5/qt3d_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5634 tasks of which 5633 didn't need to be rerun and 1 failed.

Since the package ist not needed, it can be removed.

Signed-off-by: Mario Schuknecht <mario.schuknecht@dresearch-fe.de>