gpsd: Fix compile HYP-16401
Add '-lm' to LDFLAGS, because without that gpsd compile fails (yocto/morty)
with following error:
 | ./libgpsd.so: error: undefined reference to 'atan2'
 | ./libgpsd.so: error: undefined reference to 'pow'
 | ./libgpsd.so: error: undefined reference to 'sqrt'
 | ./libgpsd.so: error: undefined reference to 'sin'
 | ./libgpsd.so: error: undefined reference to 'cos'
 | collect2: error: ld returned 1 exit status

Signed-off-by: Mario Schuknecht <mario.schuknecht@dresearch-fe.de>